nightlight:
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.nightlight
        color_name: "red"
    - delay:
        minutes: 1
    - service: light.turn_off
      data:
        entity_id: light.signal_jar