message_temperature_ecobee:
  sequence:
    - service: notify.ecobee
      data_template:
        message: "The main floor current temperature is {{ states('sensor.main_floor_temperature') }}"
message_temperature_push:
  sequence:
    - service: notify.ben
      data_template:
        message: "The main floor current temperature is {{ states('sensor.main_floor_temperature') }}"
    - service: notify.ben_cmstormtrooper
      data_template:
        message: "The main floor current temperature is {{ states('sensor.main_floor_temperature') }}"