motion_sleeping_night:
  sequence:
  - service: script.turn_off
    data:
      entity_id: script.s_motion_sleeping_night_timer
  - service: light.lifx_set_state
    data:
      entity_id:
        - light.switch
        - light.wall
        - light.megadesk
        - light.sink
      brightness: 50
      color_name: "red"
      transition: 2
      power: on
  - service: light.turn_on
    data:
      entity_id:
        - light.nightlight
      color_name: "red"
  - service: script.turn_on
    data:
      entity_id: script.motion_sleeping_night_timer