arlo_record_porch:
  sequence:
  - service: ifttt.trigger
    data: {"event":"arlo_record_porch"}
  - service: notify.ben
    data_template:
      title: "ARLO RECORD"
      message:  "Arlo is now recording the porch" 