arlo_record_crate:
  sequence:
  - service: ifttt.trigger
    data: {"event":"arlo_record_crate"}
  - service: notify.ben
    data_template:
      title: "ARLO RECORD"
      message:  "Arlo is now recording the crate" 